apiVersion: v1
kind: Pod
metadata:
  name: busybox-prod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
  restartPolicy: Never
